molgenis/molgenis-ops-helm

charts/molgenis-jenkins/README.md
charts/molgenis-jenkins/templates/config.tpl
charts/molgenis-jenkins/values.yaml

Found out that the git user config is hidden in hudson.plugins.git.GitSCM.xml.
Script it from values

feat(jenkins): Configure git user

---

charts/molgenis-hubot/Chart.yaml
charts/molgenis-hubot/README.md
charts/molgenis-hubot/values.yaml

Add preview script which allows you to install, list and delete preview instances of molgenis using a jenkins job
Reorganize the configuration information in the README as little bit so I can add the config for the script.

feat(hubot): Add preview script

---

charts/molgenis-jenkins/values.yaml

[FEAT] Updated Jenkins environment to also maintain registries

---

charts/molgenis/Chart.yaml
charts/molgenis/templates/ingress.yaml

Check: https://appscode.com/products/voyager/7.1.1/guides/ingress/http/http2/

[FEATURE] enable http2 for MOLGENIS

---

charts/molgenis-jenkins/values.yaml
charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/values.yaml
charts/molgenis-vault/values.yaml

[FEAT] Set resource limits to achieve quality of service guarantees

---

charts/molgenis-elasticsearch/Chart.yaml
charts/molgenis-elasticsearch/templates/deployment.yaml
charts/molgenis-elasticsearch/templates/pvc.yaml
charts/molgenis-elasticsearch/values.yaml

Use standard pvc template, update values.yaml to remove master

[FEAT] Support storage class in elasticsearch values

---

charts/molgenis/README.md

* Add high-level consistency remarks
* Remove low-level value documentation, they are documented in the question descriptions.

doc(molgenis): Update README

---

charts/molgenis-jenkins/resources/nightly/Jenkinsfile
charts/molgenis-jenkins/values.yaml

[JENKINS][CHORE] Remove IT and API tests and added nightly

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

Allows creation of R pods with label r-3.5.2 based on rocker/verse:3.5.2.

feat(jenkins): add r pod template

---

charts/molgenis-jenkins/resources/preview/Jenkinsfile
charts/molgenis-jenkins/resources/tests/e2e/Jenkinsfile
charts/molgenis-jenkins/resources/tests/nightly/Jenkinsfile
charts/molgenis/Chart.yaml
charts/molgenis/templates/deployment.yaml

fix(molgenis): read proper sentry values

---

charts/molgenis-jenkins/resources/preview/Jenkinsfile

chart name is unique
version is always latest (good for previews)

fix(jenkins): upgrade preview job to rancher 2.2

---

charts/molgenis-frontend/Chart.yaml
charts/molgenis-frontend/templates/ingress.yaml

admittedly a somewhat arbitrary list

fix(frontend): Add more status codes

---

ingress/README.md
ingress/daemonset.yaml
ingress/nginx-template.yaml

Document how we override the X-Forwarded-Port header

doc(ingress): document ingress port override

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

See here for name and version: https://plugins.jenkins.io/token-macro

fix(jenkins): upgrade token-macro plugin

---

charts/molgenis-logging/Chart.yaml
charts/molgenis-logging/templates/secret-elasticsearch.yaml
charts/molgenis-logging/templates/secret-kibana.yaml
charts/molgenis-logging/values.yaml

Added quotes and b64enc statements to the helm values to resolve secret problem.

[Molgenis-logging][FIX] Password store fix

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

feat: add sonar container to shared pod template

---

charts/molgenis-ols/.helmignore
charts/molgenis-ols/Chart.yaml
charts/molgenis-ols/README.md
charts/molgenis-ols/questions.yml
charts/molgenis-ols/templates/NOTES.txt
charts/molgenis-ols/templates/_helpers.tpl
charts/molgenis-ols/templates/deployment.yaml
charts/molgenis-ols/templates/ingress.yaml
charts/molgenis-ols/templates/secret-ols.yaml
charts/molgenis-ols/templates/service.yaml
charts/molgenis-ols/templates/tests/test-connection.yaml
charts/molgenis-ols/values.yaml

Branch for testing OLS for if we want to put it in production.

Feat: Molgenis-ols test initiative

---

README.md
charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

feat(jenkins): add build status plugin

---

charts/molgenis-vault/README.md

docs(vault): add deployment configuration

---

charts/molgenis-jenkins/resources/tests/nightly/Jenkinsfile

chore(nightly): updated chart version

---

charts/molgenis-vault/Chart.yaml
charts/molgenis-vault/README.md
charts/molgenis-vault/questions.yml
charts/molgenis-vault/resources/backup.yaml
charts/molgenis-vault/resources/restore.yaml
charts/molgenis-vault/values.yaml

fix(vault): added port 9000 to Minio endpoint

---

charts/molgenis-hubot/Chart.yaml
charts/molgenis-hubot/questions.yaml
charts/molgenis-hubot/values.yaml
charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/templates/config.tpl

chore(hubot): add questions

---

charts/molgenis-jenkins/resources/preview/Jenkinsfile
charts/molgenis/Chart.yaml
charts/molgenis/templates/deployment.yaml
charts/molgenis/values.yaml

fix(runtime-env): added runtime environment for logging purposes

---

charts/molgenis/questions.yml

Change the default sentry dns to the current one

chore(molgenis): Update questions.yml

---

charts/molgenis-frontend/Chart.yaml
charts/molgenis-frontend/values.yaml

fix(frontend): add proxy body size annotation

---

charts/molgenis-frontend/Chart.yaml
charts/molgenis-frontend/templates/configmaps/proxy-backend.yaml

fix(frontend): allow large requests to backend

---

charts/molgenis-vault/Chart.yaml
charts/molgenis-vault/values.yaml

chore(backup): backup vault each day

---

charts/molgenis-vault/Chart.yaml
charts/molgenis-vault/resources/vault-nodeport.yaml

fix(vault): only publish ready endpoints

---

charts/molgenis-grafana/Chart.yaml
charts/molgenis-grafana/values.yaml
charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/values.yaml

[FEAT] Add postgresql dashboard

---

charts/lifelines-edge/.helmignore
charts/lifelines-edge/Chart.yaml
charts/lifelines-edge/app-readme.md
charts/lifelines-edge/questions.yml
charts/lifelines-edge/templates/NOTES.txt
charts/lifelines-edge/templates/_helpers.tpl
charts/lifelines-edge/templates/config.yaml
charts/lifelines-edge/templates/deployment.yaml
charts/lifelines-edge/templates/ingress.yaml
charts/lifelines-edge/templates/secret.yaml
charts/lifelines-edge/templates/service.yaml
charts/lifelines-edge/values.yaml

[FEAT] Lifelines edge server

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

feat(jenkins): add node-dubnium pod, upgrade node-carbon pod

---

charts/lifelines-edge/Chart.yaml
charts/lifelines-edge/questions.yml
charts/lifelines-edge/templates/config.yaml
charts/lifelines-edge/templates/secret.yaml
charts/lifelines-edge/values.yaml

feat: add dataplatform to lifelines

---

charts/molgenis-elasticsearch/Chart.yaml
charts/molgenis-elasticsearch/templates/deployment.yaml

feat(elasticsearch): upgrade to k8s 16

---

charts/molgenis-frontend/Chart.yaml
charts/molgenis-frontend/templates/deployment.yaml
charts/molgenis-frontend/templates/ingress.yaml

feat(frontend): upgrade api versions to k8s 16

---

charts/molgenis-opencpu/Chart.yaml
charts/molgenis-opencpu/questions.yml
charts/molgenis-opencpu/values.yaml

fix(opencpu-tag): bump opencpu version to 2.1.4

---

charts/lifelines-webshop/Chart.yaml
charts/lifelines-webshop/questions.yaml
charts/lifelines-webshop/values.yaml

fix(lifelines-webshop): fix edge server proxy

---

charts/lifelines-webshop/Chart.yaml
charts/lifelines-webshop/values.yaml

fix(lifelines-webshop): add path to proxy config

---

charts/lifelines-webshop/values.yaml

task(lifelines-webshop): bump transform image version from 0.5.2 to 0.5.3

task(lifelines-webshop): bump transform image version

---

charts/lifelines-webshop/Chart.yaml

chore(lifelines-webshop): bump version

---

charts/molgenis-elasticsearch/Chart.yaml
charts/molgenis-elasticsearch/templates/deployment.yaml

Also done in docker-compose: https://github.com/molgenis/docker/pull/62/files

fix: disable monitoring and watcher functionality

---

charts/molgenis-elasticsearch/Chart.yaml
charts/molgenis-elasticsearch/templates/deployment.yaml

elasticsearch: fix ulimits warnings

---

charts/molgenis-frontend/Chart.yaml
charts/molgenis-frontend/templates/deployment.yaml
charts/molgenis-frontend/templates/proxy-configmap.yaml
charts/molgenis-frontend/values.yaml

fix: frontend proxy override can be set to false when needed

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

fix: switch to /bin/bash for more process handling options

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

fix(jenkins): only set HOME dir in rancher and maven pods

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

fix(jenkins): add build-token-root plugin

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

FIX: reintroduce jdk8 pod

---

charts/molgenis-frontend/Chart.yaml
charts/molgenis-frontend/README.md
charts/molgenis-frontend/templates/deployment.yaml
charts/molgenis-frontend/templates/proxy-configmap.yaml
charts/molgenis-frontend/values.yaml

feat(frontend): total control over proxy.d conf

---

charts/molgenis-frontend/Chart.yaml
charts/molgenis-frontend/templates/proxy-configmap.yaml

fix(frontend): proper indent of configmap

---

charts/molgenis-jenkins/Chart.yaml

chore(molgenis-jenkins): bump version to 1.1.0

---

charts/molgenis-datashield/Chart.yaml
charts/molgenis-datashield/questions.yml

fix: rename molgenis.uri to server.config.molgenis.uri

---

charts/molgenis-datashield/Chart.yaml
charts/molgenis-datashield/questions.yml
charts/molgenis-datashield/templates/_helpers.tpl
charts/molgenis-datashield/templates/deployment.yaml
charts/molgenis-datashield/values.yaml

fix: minio url

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

feat(jenkins): add r-3.6.2 pod

---

charts/molgenis-nexus/Chart.yaml
charts/molgenis-nexus/questions.yml
charts/molgenis-nexus/templates/deployment.yaml
charts/molgenis-nexus/templates/ingress.yaml
charts/molgenis-nexus/values.yaml

changed:
- deployment.yml to api apps/v1
- ingress.yml to networking.k8s.io/v1beta1
- values.yml: sonatype/nexus3:3.22.0

feat(nexus3): update: 

---

charts/molgenis-grafana/Chart.yaml
charts/molgenis-grafana/values.yaml

fix(grafana) dashboards to master urls

---

charts/molgenis-grafana/Chart.yaml
charts/molgenis-grafana/questions.yml

bump(grafana): bumped chart
fix(grafana) changed questions to map vars
fix(grafana) other notation in questions
fix(grafana) changed type string to array questions
fix(grafana) added subquestion for root_url
fix(grafana) escaped underscore
fix(grafana) quoted variable
fix(grafana) escaped dot
fix(grafana) test changes
feat(grafana) added instructions for working deploy

fix(grafana) changed redirect github variable

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/templates/getTargets-cronjob.yaml

fix(prometheus) set cronjob to 30 5 * * *

---

charts/lifelines-webshop/Chart.yaml
charts/lifelines-webshop/questions.yaml
charts/lifelines-webshop/templates/transform-cron.yaml
charts/lifelines-webshop/values.yaml

fix: update lifelines chart

---

charts/lifelines-webshop/templates/transform-cron.yaml

fix: update transform mount path

---

charts/molgenis-grafana/Chart.yaml
charts/molgenis-grafana/values.yaml
charts/molgenis-oauth2/Chart.yaml
charts/molgenis-oauth2/values.yaml

changed github team-ids of:
- molgenis-grafana
- molgenis-oauth

Fix: helm github team ids

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

feat: add node-erbium pod

---

charts/molgenis-datashield/Chart.yaml
charts/molgenis-datashield/questions.yml
charts/molgenis-datashield/values.yaml

fix(datashield): Make ready for demo

---

charts/lifelines-webshop/values.yaml
charts/vue-pdfium/templates/deployment.yaml

fix: custom config for lifelines-webshop

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

fix(jenkins): upgrade a bit more

---

charts/filebeat/Chart.yaml
charts/filebeat/values.yaml

Molgenis filebeat

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/scripts/targetWebGet.sh

feat(prometheus) added missing targets not in inventory

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/templates/getTargets-cronjob.yaml

- cronjob get wrong script
- bumped chart

fix(prometheus) fixed:

---

charts/molgenis-logging/Chart.yaml
charts/molgenis-logging/values.yaml

elasticsearch master +1gb heap size

---

charts/filebeat/Chart.yaml
charts/filebeat/values.yaml

filebeat: multiline pattern fix

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/templates/serverfiles-configmap.yaml

- added postgres/elasticsearch/molgenis exporters entrance
- bumped chart

feat(prometheus) dev

---

charts/molgenis-logging/Chart.yaml
charts/molgenis-logging/values.yaml

- proxy-body-size to 10m
- bumped chart version to 0.4.1

fix(logging) changed:

---

.gitignore
charts/molgenis-emx2/Chart.yaml
charts/molgenis-emx2/README.md
charts/molgenis-emx2/questions.yaml
charts/molgenis-emx2/templates/_helpers.tpl
charts/molgenis-emx2/templates/deployment.yaml
charts/molgenis-emx2/templates/ingress.yaml
charts/molgenis-emx2/templates/pvc.yaml
charts/molgenis-emx2/templates/svc.yaml
charts/molgenis-emx2/values.yaml

In particular, please check ingress. Any other improvements such as more questions/options are very welcome.

feat: molgenis-emx2 chart

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/templates/serverfiles-configmap.yaml

- fix wrong alerting blackbox
- bumped version in chart

fix(prometheus) changes:

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/questions.yml
charts/molgenis-armadillo/templates/deployment.yaml
charts/molgenis-armadillo/values.yaml

feat: add debug mode for RServe

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/scripts/targetWebGet.sh

- http://www.eucanconnect.eu
- http://www.eucanconnect.com
- Functionality works & meets specifications (tested on rancher)

fix(prometheus) add sites to monitoring

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/questions.yml
charts/molgenis-armadillo/templates/_helpers.tpl
charts/molgenis-armadillo/templates/config.yaml
charts/molgenis-armadillo/templates/deployment.yaml
charts/molgenis-armadillo/templates/ingress.yaml
charts/molgenis-armadillo/templates/secret.yaml
charts/molgenis-armadillo/values.yaml

feat(armadillo): configure minio and openid

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/values.yaml

fix(armadillo): set proxy body size on ingress

---

resources/ORCIDiD_iconvector.svg

feat: add orcid icon

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/templates/ingress.yaml
charts/molgenis-armadillo/values.yaml

fix: add quotes to values of ingress annotations

---

charts/molgenis-frontend/Chart.yaml
charts/molgenis-frontend/templates/proxy-configmap.yaml
charts/molgenis-frontend/values.yaml

feat(frontend): configure proxy read timeout

---

charts/lifelines-webshop/Chart.yaml
charts/lifelines-webshop/templates/transform-cron.yaml
charts/lifelines-webshop/values.yaml

fix(lifelines-webshop): add emptydir to cronjob

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/questions.yml

feat(armadillo): add question for session timeout

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/scripts/targetWebGet.sh
charts/molgenis-prometheus/templates/getTargets-cronjob.yaml

changes:
- cronjob wont work because of DNS(set dnspolicy and dnsoptions ndots:2)
- add logging to script if monitoring true/false
- bumped version chart

fix: issues with:

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/templates/deployment.yaml

fix: add tmp dir for rserve

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/resources/cleanup-excluding-frontend/Jenkinsfile
charts/molgenis-jenkins/values.yaml

- exclude frontend pr from nightly cleanup
- run clean all each month

task: Keep around the frontend pr's a bit longer

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

change cron format to more standard format, and update jenkins version

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

- Switch back to jenkins version 2.222.3
- Remove extra cleanup script
- Bump chart version to test deploy

fix: Rollback preview cleanup change

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/questions.yml
charts/molgenis-armadillo/templates/deployment.yaml
charts/molgenis-armadillo/templates/secret.yaml

feat: make datashield.seed option configurable

---

charts/fusion-auth/Chart.yaml
charts/fusion-auth/values.yaml

fix(fusion-auth): update molgenis style

---

charts/molgenis-logging/Chart.yaml
charts/molgenis-logging/values.yaml

fix(logging) enlarged heap size

---

charts/molgenis-opencpu/Chart.yaml
charts/molgenis-opencpu/templates/deployment.yaml

fix: change apiVersion in molgenis-opencpuchart

---

charts/molgenis-website/Chart.yaml
charts/molgenis-website/templates/deployment.yaml

fix apiVersion for k8s upgrade

---

charts/fusion-auth/Chart.yaml
charts/fusion-auth/questions.yml
charts/fusion-auth/values.yaml

feat: add issuer and rsa key

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/scripts/serverlistRequester.py
charts/molgenis-prometheus/templates/getTargets-cronjob.yaml
charts/molgenis-prometheus/templates/serverfiles-configmap.yaml
charts/molgenis-prometheus/templates/targets-configmap.yaml

feat(script) bash to python

---

charts/vue-pdfium/Chart.yaml
charts/vue-pdfium/templates/deployment.yaml
charts/vue-pdfium/values.yaml

changed chart to reflect new location of docker image

---

charts/molgenis/Chart.yaml
charts/molgenis/questions.yml

feat: add contact person and end of life date to deployment

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/questions.yml
charts/molgenis-armadillo/values.yaml

feat: updated rserver image name

---

charts/molgenis/Chart.yaml
charts/molgenis/questions.yml

fix: variable types in questions molgenis-chart

---

charts/variant-formatter/Chart.yaml
charts/variant-formatter/templates/deployment.yaml
charts/variant-formatter/values.yaml

feat(variant-formatter): add max workers

---

charts/molgenis/Chart.yaml
charts/molgenis/templates/deployment.yaml

Not so much a real fix as a workaround for #208 that should save people a lot of time.

fix(molgenis): check release name for 'molgenis'

---

charts/lifelines-webshop/Chart.yaml
charts/lifelines-webshop/questions.yaml

fix(lifelines): add question for frontend version

---

charts/molgenis-emx2/templates/ingress.yaml

Update ingress.yaml to enable file uploads

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/questions.yml
charts/molgenis-jenkins/values.yaml

feat: added shared library

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/questions.yml
charts/molgenis-jenkins/values.yaml

fix(jenkins): configure OIDC through env vars

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/questions.yml
charts/molgenis-armadillo/templates/deployment.yaml
charts/molgenis-armadillo/values.yaml

feat(armadillo): configure resources

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

feat(jenkins): Add R 4.0.2 build pod

---

charts/molgenis-emx2/Chart.yaml
charts/molgenis-emx2/values.yaml

to overcome pull limit (wait until image appears there before we merge)

feat: move molgenis-emx to molgenis organisation @dockerhub 

---

charts/molgenis-emx2/Chart.yaml
charts/molgenis-emx2/templates/deployment.yaml

change molgenis-emx2 params to env

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/scripts/serverlistRequester.py

added try except handling to the serverlistRequester.py

---

charts/molgenis-jenkins/resources/tests/e2e-commander/Jenkinsfile

fix(jenkins): use latest molgenis version in commander test

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/questions.yml
charts/molgenis-armadillo/templates/audit-pvc.yaml
charts/molgenis-armadillo/templates/deployment.yaml
charts/molgenis-armadillo/templates/filebeat-cfg.yaml
charts/molgenis-armadillo/templates/filebeat-pvc.yaml
charts/molgenis-armadillo/values.yaml

feat(armadillo): persist auditing

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

feat(jenkins): upgrade node containers

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

- Functionality works & meets specifications (tested on rancher)

feat(jenkins): add node-fermium build pod

---

charts/molgenis-hubot/Chart.yaml
charts/molgenis-hubot/values.yaml

- Functionality works & meets specifications (tested on rancher)

fix(hubot): update preview message

---

charts/molgenis-auth/Chart.yaml
charts/molgenis-auth/questions.yml
charts/molgenis-auth/values.yaml

fix(molgenis-auth): rename image to molgenis-auth

---

charts/kes/README.md

doc(kes): make README clearer

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/questions.yml

feat(armadillo): set prod certificate as default

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

fix(jenkins): set ttyEnabled in jdk13 pod

---

charts/molgenis-auth/Chart.yaml
charts/molgenis-auth/templates/config.yaml
charts/molgenis-auth/templates/deployment.yaml

feat: molgenis-auth usable as subchart

---

charts/molgenis-auth/Chart.yaml
charts/molgenis-auth/templates/config.yaml
charts/molgenis-auth/values.yaml

fix: remove redirect url

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/templates/deployment.yaml

fix(armadillo): env var for clientId

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

fix(jenkins): upgrade casc plugin

---

Jenkinsfile
charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

Blocks on: https://github.com/molgenis/molgenis-ops-docker/pull/67

feat: add maven jdk15 build pod and gradle jdk 15 build pod

---

Jenkinsfile
charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

Makes for speedier PR tests with less clutter.
Does mean that if there are NO changes, the build fails

chore: only test changed charts

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

fix(jenkins): upgrade chart tester

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/questions.yml

changes:
- slack webhook(deprecated) for slack app

slack integration change

---

charts/molgenis-website/Chart.yaml
charts/molgenis-website/questions.yml
charts/molgenis-website/templates/deployment.yaml
charts/molgenis-website/values.yaml

feat(website): added pull secret

---

charts/molgenis/Chart.yaml
charts/molgenis/questions.yml
charts/molgenis/templates/deployment.yaml
charts/molgenis/values.yaml

feat(molgenis): configure max file upload

---

charts/molgenis/Chart.yaml
charts/molgenis/templates/deployment.yaml

Speed up probes of molgenis pod

---

charts/molgenis-logging/Chart.yaml
charts/molgenis-logging/README.md
charts/molgenis-logging/templates/_helpers.tpl
charts/molgenis-logging/templates/job-bootstrap.yaml

fix(logging): allow other release names

---

charts/molgenis/Chart.yaml
charts/molgenis/questions.yml
charts/molgenis/templates/deployment.yaml
charts/molgenis/templates/filebeat-cfg.yaml
charts/molgenis/values.yaml

feat: send audit logging to elasticsearch

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/scripts/serverlistRequester.py

replacement vm for downtime(temporarely)(merge when mol122 is working as serverlist)

---

charts/molgenis/Chart.yaml
charts/molgenis/values.yaml

fix: repository for commander

---

charts/molgenis-logging/Chart.yaml
charts/molgenis-logging/templates/job-bootstrap.yaml

fix(molgenis-logging): use correct filebeat version

---

charts/molgenis-elasticsearch/Chart.yaml
charts/molgenis-elasticsearch/templates/deployment.yaml

set xpack components enable to false

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/scripts/serverlistRequester.py

revert to serverlist.gcc.rug.nl

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

fix: remove x-pack from elasticsearch in jenkins

---

charts/molgenis-elasticsearch/Chart.yaml
charts/molgenis-elasticsearch/templates/deployment.yaml

fix: xpack settings in deployment

---

charts/molgenis/Chart.yaml
charts/molgenis/templates/commander-job.yaml
charts/molgenis/templates/oidc-job.yaml

fix: username and password for commander

---

charts/molgenis/Chart.yaml
charts/molgenis/questions.yml
charts/molgenis/values.yaml

fix: commander and oidc default false

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

feat: added multiple base images and toolset from redhat

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/README.md
charts/molgenis-prometheus/templates/serverfiles-configmap.yaml

- scrapes openstack23 work via cmdb
- updated alerts
- updated README new slack apps

prometheus changes:

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/questions.yml
charts/molgenis-jenkins/values.yaml

fix(jenkins): upgrade to 2.289

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

fix(jenkins): approve putAt method

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

fix(jenkins): remove unsafe putAt script approval

---

charts/molgenis/Chart.yaml
charts/molgenis/questions.yml
charts/molgenis/templates/commander-config.yaml
charts/molgenis/templates/commander-job.yaml
charts/molgenis/templates/oidc-config.yaml
charts/molgenis/templates/oidc-job.yaml
charts/molgenis/values.yaml

fix(molgenis): upgrade to molgenis-commander 2.0.0

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/questions.yml
charts/molgenis-armadillo/values.yaml

feat: make the rserver repository more lenient

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/templates/serverfiles-configmap.yaml
charts/molgenis-prometheus/values.yaml

added different routes to notify ssl alert only once a day

added alert ssl expire to prometheus

---

charts/molgenis-hubot/Chart.yaml
charts/molgenis-hubot/values.yaml

feat(hubot): added hubot cleanup script

---

charts/jupyterhub/Chart.yaml
charts/jupyterhub/values.yaml

timeout forever

---

charts/molgenis/Chart.yaml
charts/molgenis/questions.yml
charts/molgenis/values.yaml

- Functionality works & meets specifications (tested on rancher)

fix(molgenis): remove deprecated java opts Is needed to run jdk 17 base image

---

charts/molgenis-rserve/Chart.yaml
charts/molgenis-rserve/questions.yml

fix(rserve): typo fixed 'debug'

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/questions.yml

feat(armadillo): make resources configurable, align sessions timeout, randomize seed option

---

charts/molgenis-elasticsearch/Chart.yaml
charts/molgenis-elasticsearch/values.yaml

fix: set system property to prevent JNDI lookups

---

charts/molgenis/Chart.yaml
charts/molgenis/questions.yml

fix: added defaults from chart to questions

---

charts/molgenis-logging/Chart.yaml
charts/molgenis-logging/values.yaml

- added protection log4j vulnerability

[SECURITY FIX]

---

charts/molgenis-elasticsearch/Chart.yaml
charts/molgenis-elasticsearch/questions.yml
charts/molgenis-elasticsearch/values.yaml

feat: upgrade elasticsearch to 7.16.2

---

charts/molgenis-prometheus/Chart.yaml
charts/molgenis-prometheus/templates/serverfiles-configmap.yaml

fix(prometheus): added for: 5m to node_exporter alerts

---

charts/molgenis-armadillo/Chart.yaml
charts/molgenis-armadillo/questions.yml
charts/molgenis-armadillo/values.yaml

fix(armadillo): fix seed option configuration

---

Jenkinsfile

chore: update to external podtemplate

---

charts/molgenis-jenkins/Chart.yaml

fix: bump version molgenis-jenkins

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

fix: pod templates to high

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

ansible back in and updated with ubuntu 22.04

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/resources/tests/e2e-commander/Jenkinsfile

fix(e2e-commander): update pod template

---

charts/molgenis-jenkins/Chart.yaml
charts/molgenis-jenkins/values.yaml

bumped molgenis-jenkins chart version

fix: removed ansible pod

---

charts/jupyterhub/Chart.yaml
charts/jupyterhub/questions.yml
charts/jupyterhub/values.yaml

- added question.yaml
- added Values.yaml

feat(jupyterhub): add session configuration(Sido)

---

charts/nfs/Chart.yaml
charts/nfs/questions.yaml
charts/nfs/values.yaml

fix(nfs): be able to point to the default storage class

---

charts/molgenis-logging/Chart.lock
charts/molgenis-logging/Chart.yaml
charts/molgenis-logging/requirements.yaml

- removed v2 requirements
- added Chart.lock
- bumped version Chart.yaml

- feat(logging): helm charts to v3

---

charts/molgenis-grafana/Chart.lock
charts/molgenis-grafana/Chart.yaml
charts/molgenis-grafana/requirements.yaml

- bumped version chart
- removed not used files
- added in Chart.lock

- feat(grafana): helm to v3

---

charts/molgenis-nexus/Chart.yaml

- feat(nexus3): helm to v3

---

charts/molgenis-oauth2/Chart.lock
charts/molgenis-oauth2/Chart.yaml
charts/molgenis-oauth2/requirements.lock
charts/molgenis-oauth2/requirements.yaml

- feat(oauth2): helm to v3

---

charts/molgenis-rserve/Chart.yaml

feat: rserve helm 2to3

---

charts/molgenis-elasticsearch/Chart.yaml
charts/molgenis-elasticsearch/templates/ingress.yaml

- bumped version chart
- changed ingress to v1

- elasticsearch: helm 2to3
