charts/molgenis-jenkins/templates/config.tpl, charts/molgenis-jenkins/templates/molgenis-jenkins-github-token-secret.yaml
The Git Server configuration needs the user as a secretText token, not a usernamePassword.
So add this as a kubernetes secret and use it in github-plugin-configuration.xml.
=> feat(jenkins): Script Git Server configuration

charts/molgenis/Chart.yaml, charts/molgenis/values.yaml
Starting memory was higher than max memory, causing small instances to refuse to start.
=> fix(molgenis): Set elasticsearch starting memory to correct value.

charts/molgenis-jenkins/Chart.yaml, charts/molgenis-jenkins/values.yaml
Use the 0.7.0 image because of https://github.com/GoogleContainerTools/kaniko/issues/641
Use debug image because we need to run sh and the default image is extremely slim.
=> feat(jenkins): add kaniko image to shared pod

charts/molgenis-frontend/Chart.yaml, charts/molgenis-frontend/questions.yml, charts/molgenis-frontend/templates/NOTES.txt, charts/molgenis-frontend/templates/_helpers.tpl, charts/molgenis-frontend/templates/ingress.yaml, charts/molgenis-frontend/values.yaml
Otherwise the rancher client doesn't know when the chart is deployed.
=> [FEAT] [molgenis-frontend]: determine host based on environment and add notes.txt

charts/molgenis-jenkins/resources/tests/e2e-commander/Jenkinsfile, charts/molgenis-jenkins/resources/tests/e2e/Jenkinsfile, charts/molgenis-jenkins/resources/tests/live/Jenkinsfile
There are multiple apps named 'molgenis', use the full app id to avoid conflicts
=> [JENKINS][FIX]: Use full app id

charts/molgenis-vault/Chart.yaml, charts/molgenis-vault/questions.yml
If the s3 credentials contain special characters, the backup and restore will fail.
Add a description to warn the user about this.
This is a workaround for #199
=> fix(vault): warn about special characters

charts/molgenis-jenkins/Chart.yaml, charts/molgenis-jenkins/resources/preview/Jenkinsfile, charts/molgenis-jenkins/resources/tests/e2e-commander/Jenkinsfile, charts/molgenis-jenkins/resources/tests/e2e/Jenkinsfile, charts/molgenis-jenkins/resources/tests/live/Jenkinsfile, charts/molgenis-jenkins/values.yaml
It is the default context already and switching currently is broken because there are
two contexts named molgenis-dev
=> fix(jenkins): do not switch to molgenis-dev

charts/molgenis-frontend/Chart.yaml, charts/molgenis-frontend/templates/deployment.yaml, charts/molgenis-frontend/values.yaml
Pinging on / is problematic since it's proxying the backend.
Make liveness a simple TCP port probe and readiness a check to see if a
small but vital resource is being served.
=> fix(frontend): simpler liveness and readiness probes

charts/molgenis-frontend/Chart.yaml, charts/molgenis-frontend/templates/basic-auth.yaml, charts/molgenis-frontend/templates/ingress.yaml, charts/molgenis-frontend/values.yaml
For lifelines we manually added basic auth security to the deployment.
Here, add it to the frontend chart.
As followup, need to upgrade the frontend subchart in molgenis chart.
It would be nice to generate the secret's auth key from username and password values but the `htpasswd` tool is not very clear on how that works, looks like it involves salting and hashing so it's probably a bit much for the poor sprig library to do on its own.
As an example: `user:$apr1$l7C4YghF$3duSgjvZ5FUJEMrhHoscq.` represents username `user` and password `password`.
=> feat(molgenis-frontend): allow basic auth security

charts/molgenis-hubot/Chart.yaml, charts/molgenis-hubot/values.yaml
Adds a `pr` command that automatically finds the last tag of a pull request and previews it:
```
bot preview pr 2348
```
Other tags can still be used with the 'tag' syntax:
```
bot preview tag PR-2348-2
```
=> feat(hubot): Add 'preview pr' command

charts/molgenis-jenkins/Chart.yaml, charts/molgenis-jenkins/values.yaml
The organisation scan needs to finish before the health checks begin to fail
=> fix(jenkins): drastically increase health probe timeouts

charts/fusion-auth/Chart.yaml, charts/fusion-auth/questions.yml, charts/fusion-auth/values.yaml
Adds a theme called `MOLGENIS Blue` at boot time using a kickstart script.
First copies the default theme and then overwrites the necessary theme fields.
To see it in action, edit the Default tenant and select the theme.
Helm is a bit clunky, so we have to inline the files into values.yaml, and cannot provide yaml to convert to kickstart.json either. But we can feed the api key to create from questions right into the script through an environment variables.
I noticed that the subchart got upgraded and this one cannot yet handle kubernetes 1.16.
So I had to test on the dev cluster.
When upgrading you also have to start providing your own elasticsearch and postgres so I suggest to do that in a different PR.
=> feat(fusion-auth): add molgenis blue theme

charts/lifelines-webshop/Chart.yaml, charts/lifelines-webshop/questions.yaml, charts/lifelines-webshop/values.yaml
Update the default path to sync with the path as expected by the app ans used in PROD and ACC environments
=> fix: Lifelines default app proxy path

charts/molgenis-jenkins/Chart.yaml, charts/molgenis-jenkins/questions.yml, charts/molgenis-jenkins/values.yaml
Done because kubernetes plugin does not respond correctly when there is much load on the cluster.
Kubernetes plugin version 1.27.3 contains concurrency fixes which hopefully help solving the problem.
=> fix(jenkins): update plugins

charts/molgenis-jenkins/Chart.yaml, charts/molgenis-jenkins/values.yaml
The armadillo build was broken cause it no longer could deploy the latest version to the dev cluster.
I think we were running into an issue with the rancher cli, cause the same command did work from the command line on my laptop.
=> feat(jenkins): upgrade rancher cli in shared build pod to 2.4.10

charts/molgenis-armadillo/Chart.yaml, charts/molgenis-armadillo/README.md, charts/molgenis-armadillo/templates/kes-certificate-identity-job.yaml, charts/molgenis-armadillo/templates/kes-key-create-job.yaml, charts/molgenis-armadillo/values.yaml
Creates two jobs.
First job computes the client key identity so you can easily update the kes server's policy.
Second job keeps trying to create the key, once the kes server has been upgraded it will succeed
=> Make KES key creation easier in Armadillo

charts/molgenis-armadillo/Chart.yaml, charts/molgenis-armadillo/templates/kes-key-create-job.yaml
Will now create a single pod that keeps trying to create the key with increasing backoff times.
The times are not configurable in k8s but in practice it keeps increasing until you reach 6 minutes.
The pod keeps retrying twenty times, that should give you plenty time to configure the kes server.
=> fix(armadillo): restart kes pod on failure

charts/molgenis/Chart.yaml, charts/molgenis/templates/oidc-secret.yaml
In molgenis/molgenis#9320 I updated the enum value from `basic` to `client_secret_basic` because spring security deprecated `basic`, but I forgot all about the job
=> fix(molgenis): update openid basic -> client_secret_basic

charts/molgenis-jenkins/resources/tests/nightly/Jenkinsfile
The nightly build has broken since https://jenkins.dev.molgenis.org/job/test-nightly/512/ because spring updated some plugin versions.
Also, since jdk17 it needs to build in jdk17 maven build pod.
This uses the new pod added to the jenkins pipeline library.
- Templates reviewed
- Bumped the chart version
=> chore: fix nightly build

charts/molgenis-jenkins/resources/tests/e2e-commander/Jenkinsfile
De build faalt nog steeds omdat hij een chart bump wil. Dat hoeft niet omdat dit geen resources zijn die met de chart worden uitgerold. Dit wordt elke nacht opgevraagd door de commander job en is alleen van belang voor de jobconfig.
=> fix: commander test namespace
